//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookPortalBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardDetail
    {
        public int AwardId { get; set; }
        public int BookId { get; set; }
        public int AuthorId { get; set; }
        public string AwardName { get; set; }
        public string AwardDescription { get; set; }
        public Nullable<System.DateTime> AwardRecievedDate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookMaster BookMaster { get; set; }
    }
}
